GitHub Project Information

maria-korosteleva/Garment-Pattern-Estimation
Stars: 181
Forks: 21
Last Commit Date: December 23, 2024

tf-encrypted/tf-encrypted
Stars: 1.2k
Forks: 211
Last Commit Date: September 25, 2024

baggepinnen/SpectralDistances.jl
Stars: 49
Forks: 5
Last Commit Date: January 15, 2026

MassimoCimmino/pygfunction
Stars: 72
Forks: 26
Last Commit Date: August 4, 2025

the-virtual-brain/tvb-root
Stars: 190
Forks: 151
Last Commit Date: September 23, 2026

Xtra-Computing/thundergbm
Stars: 715
Forks: 88
Last Commit Date: March 19, 2025

iTowns/itowns
Stars: 1.3k
Forks: 317
Last Commit Date: September 14, 2026

Serock3/Master-Thesis-QEC-simulation
Stars: 5
Forks: 0
Last Commit Date: September 7, 2024

raysect/source
Stars: 112
Forks: 25
Last Commit Date: August 25, 2025

nimble-dev/nimble
Stars: 198
Forks: 27
Last Commit Date: August 31, 2026

In [ ]:
!python -m pip install -U python-woc pandas matplotlib

In [ ]:
%pip install python-woc

In [1]:
from woc.remote import WocMapsRemote
from tqdm import tqdm
import pandas as pd
# creates the client
woc = WocMapsRemote( base_url="https://worldofcode.org/api/")
# if you got an API key
# woc = WocMapsRemote( base_url="https://worldofcode.org/api/", api_key="woc-XXXXXX-YYYYYY" )

# Now for each of the ten projects you were assigned get commits, e.g.
projects = [
    'maria-korosteleva/Garment-Pattern-Estimation',
    'tf-encrypted/tf-encrypted',
    'baggepinnen/SpectralDistances.jl',
    'MassimoCimmino/pygfunction',
    'the-virtual-brain/tvb-root',
    'Xtra-Computing/thundergbm',
    'iTowns/itowns',
    'Serock3/Master_thesis_QEC_simulation',
    'raysect/source',
    'nimble-dev/nimble'
]
list_df_commits = []
for prj in projects:
  # Convert GitHub repository names to WoC V2412 project names
  prj = prj.lower().replace('/','_',2)
  commits = woc.get_values('p2c', prj)
  df = pd.DataFrame(commits, columns=["sha1"])
  df['project'] = prj
  list_df_commits.append(df)
df = pd.concat(list_df_commits)
#perhaps save the list (if no errors) so you do not need to retrieve them again
df.to_csv('df_commits.csv')
df.head(1)

,sha1,project
0,005873aebe765beedd8bb2cda3184f8c89279d21,maria-korosteleva_garment-pattern-estimation

In [2]:
# If the number of commits its not very large, you can try to get them all at the same time,
# The max batch size is 10
import time
# let us first split df['sha1'] in chunks
chunks = [df['sha1'][x:x+10] for x in range(0, len(df), 10)]commit_data = []

for chunk in tqdm(chunks): # iterate over the commits
  # res, err = woc.show_content_many('commit',chunk.to_list())

  # commit.tch returns the same data but faster
  res, err = woc.get_values_many('commit.tch',chunk.to_list())
  res = {k: v[0] for k, v in res.items()}  # this conversion is necessary because of the internal implementation

  # to walk around the rate limit
  time.sleep(1)

  if err: # check for errors
    print('Got Errors', err)

  for commit_sha, commit in res.items():
    # flatten commit objects
    commit_data.append({
          'commit': commit_sha,
          'tree': commit[0],
          'parent': list(commit[1]),
          'author': commit[2][0],
          'author_time': int(commit[2][1]),
          'author_tz': commit[2][2],
          'committer': commit[3][0],
          'committer_time': int(commit[3][1]),
          'committer_tz': commit[3][2],
          'message': commit[4],
    })

df_commit_data = pd.DataFrame(commit_data)
df_commit_data = df_commit_data.merge(df, left_on='commit', right_on='sha1')
df_commit_data.to_csv('df_commit_data.csv', index=False)
df_commit_data.head(2)

 45%|███████████████████████████████████▍                                          | 1797/3955 [30:52<37:01,  1.03s/it]

Got Errors {'078aaf982f95af593cf547da4fb8b526ec916441': 'Key 078aaf982f95af593cf547da4fb8b526ec916441 not found in /da5_fast/All.sha1c/commit_7.tch'}

 46%|███████████████████████████████████▌                                          | 1803/3955 [30:59<37:01,  1.03s/it]

Got Errors {'0959f291d2d158b9e818ab41836beaa1cfa4670b': 'Key 0959f291d2d158b9e818ab41836beaa1cfa4670b not found in /da5_fast/All.sha1c/commit_9.tch'}

 46%|███████████████████████████████████▊                                          | 1819/3955 [31:15<36:40,  1.03s/it]

Got Errors {'0d428bf80aeae3e96dfafbc9a28bfae755d401ed': 'Key 0d428bf80aeae3e96dfafbc9a28bfae755d401ed not found in /da5_fast/All.sha1c/commit_13.tch', '0d69513ae2eb7565f87cc43b73b956f691986286': 'Key 0d69513ae2eb7565f87cc43b73b956f691986286 not found in /da5_fast/All.sha1c/commit_13.tch'}

 46%|███████████████████████████████████▉                                          | 1821/3955 [31:17<36:36,  1.03s/it]

Got Errors {'0dc662331743f36e061a1e60b230a6e9e26a7f7a': 'Key 0dc662331743f36e061a1e60b230a6e9e26a7f7a not found in /da5_fast/All.sha1c/commit_13.tch'}

 47%|████████████████████████████████████▎                                         | 1844/3955 [31:41<36:14,  1.03s/it]

Got Errors {'13e4d74fcffb6051e232b8a91d2af6a7d978beb7': 'Key 13e4d74fcffb6051e232b8a91d2af6a7d978beb7 not found in /da5_fast/All.sha1c/commit_19.tch'}

 48%|█████████████████████████████████████▋                                        | 1913/3955 [32:52<34:59,  1.03s/it]

Got Errors {'27aee93579de57c81dbc04fa366fc727d1c207b3': 'Key 27aee93579de57c81dbc04fa366fc727d1c207b3 not found in /da5_fast/All.sha1c/commit_39.tch'}

 49%|█████████████████████████████████████▉                                        | 1924/3955 [33:03<34:50,  1.03s/it]

Got Errors {'2aa2ecea47a6f3f94680919347f5756cca44a663': 'Key 2aa2ecea47a6f3f94680919347f5756cca44a663 not found in /da5_fast/All.sha1c/commit_42.tch'}

 49%|██████████████████████████████████████▍                                       | 1951/3955 [33:31<34:21,  1.03s/it]

Got Errors {'321633a906f9d820465deaae04f11277756972d6': 'Key 321633a906f9d820465deaae04f11277756972d6 not found in /da5_fast/All.sha1c/commit_50.tch'}

 50%|██████████████████████████████████████▌                                       | 1958/3955 [33:38<34:19,  1.03s/it]

Got Errors {'33c88b4602ad25bb968c45fa049eccfc5f36c330': 'Key 33c88b4602ad25bb968c45fa049eccfc5f36c330 not found in /da5_fast/All.sha1c/commit_51.tch'}

 50%|██████████████████████████████████████▋                                       | 1964/3955 [33:45<34:11,  1.03s/it]

Got Errors {'35a8ed5fbdcdb1c0099436426a07e78abaa35bd7': 'Key 35a8ed5fbdcdb1c0099436426a07e78abaa35bd7 not found in /da5_fast/All.sha1c/commit_53.tch'}

 50%|██████████████████████████████████████▉                                       | 1974/3955 [33:55<34:01,  1.03s/it]

Got Errors {'381349e65eace3f3bb9d8bac273a70f9d77ce2ca': 'Key 381349e65eace3f3bb9d8bac273a70f9d77ce2ca not found in /da5_fast/All.sha1c/commit_56.tch'}

 50%|███████████████████████████████████████▎                                      | 1996/3955 [34:17<33:34,  1.03s/it]

Got Errors {'3dec03bd8e38fc701a939a6592b0d6b8aa8ecaf7': 'Key 3dec03bd8e38fc701a939a6592b0d6b8aa8ecaf7 not found in /da5_fast/All.sha1c/commit_61.tch'}

 51%|███████████████████████████████████████▊                                      | 2020/3955 [34:42<33:19,  1.03s/it]

Got Errors {'4553ed65ff5554d9619c0724497903302bd10f0d': 'Key 4553ed65ff5554d9619c0724497903302bd10f0d not found in /da5_fast/All.sha1c/commit_69.tch'}

 51%|███████████████████████████████████████▉                                      | 2025/3955 [34:47<33:00,  1.03s/it]

Got Errors {'46b9b3e7ee88fe116b788b80164414c30025e9c2': 'Key 46b9b3e7ee88fe116b788b80164414c30025e9c2 not found in /da5_fast/All.sha1c/commit_70.tch'}

 52%|████████████████████████████████████████▊                                     | 2072/3955 [35:36<32:15,  1.03s/it]

Got Errors {'53a29b181b112a57898985323946454ea06410cb': 'Key 53a29b181b112a57898985323946454ea06410cb not found in /da5_fast/All.sha1c/commit_83.tch'}

 53%|█████████████████████████████████████████▏                                    | 2090/3955 [35:54<31:57,  1.03s/it]

Got Errors {'586b8ad048e3e768649ee8b9f4df7d2c9e0658cd': 'Key 586b8ad048e3e768649ee8b9f4df7d2c9e0658cd not found in /da5_fast/All.sha1c/commit_88.tch'}

 54%|██████████████████████████████████████████                                    | 2133/3955 [36:39<31:12,  1.03s/it]

Got Errors {'652efcda2e1bcca82e4e32967fbee685338041fc': 'Key 652efcda2e1bcca82e4e32967fbee685338041fc not found in /da5_fast/All.sha1c/commit_101.tch'}

 54%|██████████████████████████████████████████▎                                   | 2144/3955 [36:50<31:08,  1.03s/it]

Got Errors {'6836e80f3352ed44f31e1caae65305905754ef29': 'Key 6836e80f3352ed44f31e1caae65305905754ef29 not found in /da5_fast/All.sha1c/commit_104.tch'}

 55%|██████████████████████████████████████████▋                                   | 2163/3955 [37:10<30:46,  1.03s/it]

Got Errors {'6d1ff0e94aedc03b7e51de0acdab71e56400b9fe': 'Key 6d1ff0e94aedc03b7e51de0acdab71e56400b9fe not found in /da5_fast/All.sha1c/commit_109.tch'}

 56%|███████████████████████████████████████████▌                                  | 2206/3955 [37:54<30:02,  1.03s/it]

Got Errors {'79b7778d8cd7153f721a9c09a4edeff935151ecb': 'Key 79b7778d8cd7153f721a9c09a4edeff935151ecb not found in /da5_fast/All.sha1c/commit_121.tch'}

 56%|███████████████████████████████████████████▌                                  | 2212/3955 [38:00<29:58,  1.03s/it]

Got Errors {'7b2e23ca8921fa476b80878ee9e190ca717e8ffa': 'Key 7b2e23ca8921fa476b80878ee9e190ca717e8ffa not found in /da5_fast/All.sha1c/commit_123.tch'}

 56%|███████████████████████████████████████████▋                                  | 2217/3955 [38:05<29:47,  1.03s/it]

Got Errors {'7cbd0f29050f691b5a3b0ec7e45c62eaef78c363': 'Key 7cbd0f29050f691b5a3b0ec7e45c62eaef78c363 not found in /da5_fast/All.sha1c/commit_124.tch'}

 56%|███████████████████████████████████████████▉                                  | 2226/3955 [38:15<29:51,  1.04s/it]

Got Errors {'7fe02a63cef4a7792052b001025a71f3423df1d9': 'Key 7fe02a63cef4a7792052b001025a71f3423df1d9 not found in /da5_fast/All.sha1c/commit_127.tch'}

 57%|████████████████████████████████████████████▋                                 | 2268/3955 [38:58<28:47,  1.02s/it]

Got Errors {'8bfa26355034d336a2fdc896af2dbe63e6e0b77d': 'Key 8bfa26355034d336a2fdc896af2dbe63e6e0b77d not found in /da5_fast/All.sha1c/commit_11.tch'}

 59%|██████████████████████████████████████████████                                | 2334/3955 [40:06<28:24,  1.05s/it]

Got Errors {'9d6b3f5adf76e662a899e2e55c5f25b0f4215c77': 'Key 9d6b3f5adf76e662a899e2e55c5f25b0f4215c77 not found in /da5_fast/All.sha1c/commit_29.tch'}

 60%|██████████████████████████████████████████████▌                               | 2359/3955 [40:31<27:21,  1.03s/it]

Got Errors {'a4aca082f2e1519cc01e1604e3731f1f87861bb4': 'Key a4aca082f2e1519cc01e1604e3731f1f87861bb4 not found in /da5_fast/All.sha1c/commit_36.tch'}

 60%|███████████████████████████████████████████████▏                              | 2391/3955 [41:04<26:46,  1.03s/it]

Got Errors {'ad53b5e302bae34a6ae0f21d39a0ea5cdfadfe06': 'Key ad53b5e302bae34a6ae0f21d39a0ea5cdfadfe06 not found in /da5_fast/All.sha1c/commit_45.tch'}

 61%|███████████████████████████████████████████████▎                              | 2399/3955 [41:12<26:33,  1.02s/it]

Got Errors {'b02e4c06556eaa61fa72b2c3e86cc843eede557d': 'Key b02e4c06556eaa61fa72b2c3e86cc843eede557d not found in /da5_fast/All.sha1c/commit_48.tch'}

 61%|███████████████████████████████████████████████▌                              | 2409/3955 [41:23<26:24,  1.02s/it]

Got Errors {'b2e6d601e27b7d698c6d411eeff8a4c4eb8dec20': 'Key b2e6d601e27b7d698c6d411eeff8a4c4eb8dec20 not found in /da5_fast/All.sha1c/commit_50.tch'}

 61%|███████████████████████████████████████████████▌                              | 2411/3955 [41:25<26:19,  1.02s/it]

Got Errors {'b360402ab7d711b8196bb8302cc04453539a5d14': 'Key b360402ab7d711b8196bb8302cc04453539a5d14 not found in /da5_fast/All.sha1c/commit_51.tch'}

 61%|███████████████████████████████████████████████▉                              | 2428/3955 [41:42<26:10,  1.03s/it]

Got Errors {'b813790412ecd6fe1b419c8ea89429225be07105': 'Key b813790412ecd6fe1b419c8ea89429225be07105 not found in /da5_fast/All.sha1c/commit_56.tch'}

 63%|████████████████████████████████████████████████▊                             | 2474/3955 [42:29<25:20,  1.03s/it]

Got Errors {'c3f1cf4bf3cb3ce6511067105304bb403b6853c6': 'Key c3f1cf4bf3cb3ce6511067105304bb403b6853c6 not found in /da5_fast/All.sha1c/commit_67.tch'}

 63%|████████████████████████████████████████████████▉                             | 2480/3955 [42:36<25:13,  1.03s/it]

Got Errors {'c59e6ca114519f41f388f46de0fc8acf651c4d76': 'Key c59e6ca114519f41f388f46de0fc8acf651c4d76 not found in /da5_fast/All.sha1c/commit_69.tch'}

 63%|█████████████████████████████████████████████████                             | 2488/3955 [42:44<25:12,  1.03s/it]

Got Errors {'c818e95f65be089a508b79d4fb3b2fa24260b62e': 'Key c818e95f65be089a508b79d4fb3b2fa24260b62e not found in /da5_fast/All.sha1c/commit_72.tch'}

 64%|█████████████████████████████████████████████████▊                            | 2524/3955 [43:21<24:28,  1.03s/it]

Got Errors {'d285778a95d14aaf3b80301283956cfcd227f41d': 'Key d285778a95d14aaf3b80301283956cfcd227f41d not found in /da5_fast/All.sha1c/commit_82.tch'}

 64%|█████████████████████████████████████████████████▉                            | 2530/3955 [43:27<24:45,  1.04s/it]

Got Errors {'d462e84a91be2be39f361d55524741f3797541ee': 'Key d462e84a91be2be39f361d55524741f3797541ee not found in /da5_fast/All.sha1c/commit_84.tch'}

 65%|██████████████████████████████████████████████████▊                           | 2576/3955 [44:14<24:00,  1.04s/it]

Got Errors {'e08f2aa7cf0d1b08c78b3215d6ec833125e40eed': 'Key e08f2aa7cf0d1b08c78b3215d6ec833125e40eed not found in /da5_fast/All.sha1c/commit_96.tch'}

 68%|████████████████████████████████████████████████████▋                         | 2671/3955 [45:53<21:59,  1.03s/it]

Got Errors {'fa3f702abe605892d01e59e1b6eb8751cffb2959': 'Key fa3f702abe605892d01e59e1b6eb8751cffb2959 not found in /da5_fast/All.sha1c/commit_122.tch'}

 68%|████████████████████████████████████████████████████▋                         | 2672/3955 [45:54<21:58,  1.03s/it]

Got Errors {'fa8c5568ab3495f4b87ffa88cdfdbbde33a60581': 'Key fa8c5568ab3495f4b87ffa88cdfdbbde33a60581 not found in /da5_fast/All.sha1c/commit_122.tch'}

 70%|██████████████████████████████████████████████████████▉                       | 2786/3955 [47:51<20:06,  1.03s/it]

Got Errors {'35b0a3ee6f6a196bf170a7510b7ce318957b279d': 'Key 35b0a3ee6f6a196bf170a7510b7ce318957b279d not found in /da5_fast/All.sha1c/commit_53.tch'}

 71%|███████████████████████████████████████████████████████▎                      | 2805/3955 [48:11<19:59,  1.04s/it]

Got Errors {'48406f73e52a99044d4aaf3a7841c5643f736c14': 'Key 48406f73e52a99044d4aaf3a7841c5643f736c14 not found in /da5_fast/All.sha1c/commit_72.tch'}

 75%|██████████████████████████████████████████████████████████▏                   | 2952/3955 [50:42<17:10,  1.03s/it]

Got Errors {'e8f9f299d9b7bc7829780568d1bb7910c697ed6f': 'Key e8f9f299d9b7bc7829780568d1bb7910c697ed6f not found in /da5_fast/All.sha1c/commit_104.tch'}

 76%|███████████████████████████████████████████████████████████▏                  | 2998/3955 [51:30<16:25,  1.03s/it]

Got Errors {'04d00774e605a8274f33b03178dd1404bad9a1f2': 'Key 04d00774e605a8274f33b03178dd1404bad9a1f2 not found in /da5_fast/All.sha1c/commit_4.tch'}

 76%|███████████████████████████████████████████████████████████▎                  | 3008/3955 [51:40<16:16,  1.03s/it]

Got Errors {'07975c57dd222c9d742383510c4478cc92a6f36f': 'Key 07975c57dd222c9d742383510c4478cc92a6f36f not found in /da5_fast/All.sha1c/commit_7.tch'}

 76%|███████████████████████████████████████████████████████████▍                  | 3014/3955 [51:47<16:09,  1.03s/it]

Got Errors {'0953b03884d7f279376faea8d9feb52fe7578b3d': 'Key 0953b03884d7f279376faea8d9feb52fe7578b3d not found in /da5_fast/All.sha1c/commit_9.tch'}

 76%|███████████████████████████████████████████████████████████▌                  | 3022/3955 [51:55<16:00,  1.03s/it]

Got Errors {'0b34c3ccf208a692bcba907cdbb46e20ab594765': 'Key 0b34c3ccf208a692bcba907cdbb46e20ab594765 not found in /da5_fast/All.sha1c/commit_11.tch'}

 77%|███████████████████████████████████████████████████████████▋                  | 3028/3955 [52:01<15:57,  1.03s/it]

Got Errors {'0c70f3b3a472074049904be2b864449d0b9105c0': 'Key 0c70f3b3a472074049904be2b864449d0b9105c0 not found in /da5_fast/All.sha1c/commit_12.tch'}

 77%|████████████████████████████████████████████████████████████▎                 | 3056/3955 [52:30<15:29,  1.03s/it]

Got Errors {'132cd8575aad45610b427efe7c5679c18c57f04f': 'Key 132cd8575aad45610b427efe7c5679c18c57f04f not found in /da5_fast/All.sha1c/commit_19.tch'}

 77%|████████████████████████████████████████████████████████████▍                 | 3064/3955 [52:38<15:22,  1.04s/it]

Got Errors {'155b24151d228613f57cfd580a537bb4e6df6d67': 'Key 155b24151d228613f57cfd580a537bb4e6df6d67 not found in /da5_fast/All.sha1c/commit_21.tch'}

 78%|████████████████████████████████████████████████████████████▊                 | 3085/3955 [53:00<14:53,  1.03s/it]

Got Errors {'1ad983631735ab8a15aa34650d94454b944e72c3': 'Key 1ad983631735ab8a15aa34650d94454b944e72c3 not found in /da5_fast/All.sha1c/commit_26.tch'}

 79%|█████████████████████████████████████████████████████████████▎                | 3107/3955 [53:22<14:31,  1.03s/it]

Got Errors {'208411c75b59dd4e18ccd3b454e1e9e7a4ca5b99': 'Key 208411c75b59dd4e18ccd3b454e1e9e7a4ca5b99 not found in /da5_fast/All.sha1c/commit_32.tch'}

 79%|█████████████████████████████████████████████████████████████▍                | 3114/3955 [53:29<14:23,  1.03s/it]

Got Errors {'228e9b5c618dbe6a52fd1828f3cd0113a51fa4fe': 'Key 228e9b5c618dbe6a52fd1828f3cd0113a51fa4fe not found in /da5_fast/All.sha1c/commit_34.tch'}

 80%|██████████████████████████████████████████████████████████████▋               | 3180/3955 [54:38<13:18,  1.03s/it]

Got Errors {'323f96174fa2fe68b113f06845fee23997f6d1d5': 'Key 323f96174fa2fe68b113f06845fee23997f6d1d5 not found in /da5_fast/All.sha1c/commit_50.tch'}

 80%|██████████████████████████████████████████████████████████████▊               | 3183/3955 [54:41<13:15,  1.03s/it]

Got Errors {'330273fe96cd74d8f7dbf6639134d2c30d0daf4b': 'Key 330273fe96cd74d8f7dbf6639134d2c30d0daf4b not found in /da5_fast/All.sha1c/commit_51.tch'}

 81%|██████████████████████████████████████████████████████████████▉               | 3190/3955 [54:48<13:07,  1.03s/it]

Got Errors {'34d87b6af50b25bf9e32e8c1dc3029ee9c0fe5dc': 'Key 34d87b6af50b25bf9e32e8c1dc3029ee9c0fe5dc not found in /da5_fast/All.sha1c/commit_52.tch'}

 81%|███████████████████████████████████████████████████████████████▍              | 3218/3955 [55:17<12:36,  1.03s/it]

Got Errors {'3c950c7b70a1092d8a567b49b9dc32c4435308ce': 'Key 3c950c7b70a1092d8a567b49b9dc32c4435308ce not found in /da5_fast/All.sha1c/commit_60.tch'}

 82%|███████████████████████████████████████████████████████████████▋              | 3230/3955 [55:29<12:22,  1.02s/it]

Got Errors {'3fd4f3c634823be5462465950f305f8aabbed757': 'Key 3fd4f3c634823be5462465950f305f8aabbed757 not found in /da5_fast/All.sha1c/commit_63.tch'}

 82%|████████████████████████████████████████████████████████████████              | 3250/3955 [55:50<12:14,  1.04s/it]

Got Errors {'44f39991827247cd1675b8b5332b9e39eeb52df2': 'Key 44f39991827247cd1675b8b5332b9e39eeb52df2 not found in /da5_fast/All.sha1c/commit_68.tch'}

 83%|████████████████████████████████████████████████████████████████▍             | 3268/3955 [56:09<11:46,  1.03s/it]

Got Errors {'48f8a01aa3e04b56fb137c7b0fa1c09d93a2cd7c': 'Key 48f8a01aa3e04b56fb137c7b0fa1c09d93a2cd7c not found in /da5_fast/All.sha1c/commit_72.tch'}

 83%|████████████████████████████████████████████████████████████████▌             | 3275/3955 [56:16<11:40,  1.03s/it]

Got Errors {'4b04af602469a07468645bb1085d98a378d56530': 'Key 4b04af602469a07468645bb1085d98a378d56530 not found in /da5_fast/All.sha1c/commit_75.tch'}

 83%|████████████████████████████████████████████████████████████████▋             | 3277/3955 [56:18<11:39,  1.03s/it]

Got Errors {'4b67d089bff89b462ee11d6a646a3674bc03275c': 'Key 4b67d089bff89b462ee11d6a646a3674bc03275c not found in /da5_fast/All.sha1c/commit_75.tch'}

 83%|████████████████████████████████████████████████████████████████▉             | 3290/3955 [56:31<11:24,  1.03s/it]

Got Errors {'4f02705c85789893b5a14ed3be1258ca607726d8': 'Key 4f02705c85789893b5a14ed3be1258ca607726d8 not found in /da5_fast/All.sha1c/commit_79.tch'}

 84%|█████████████████████████████████████████████████████████████████▏            | 3307/3955 [56:49<11:08,  1.03s/it]

Got Errors {'53917916d7c000f7bd85dc87db0225ed08db0129': 'Key 53917916d7c000f7bd85dc87db0225ed08db0129 not found in /da5_fast/All.sha1c/commit_83.tch'}

 85%|██████████████████████████████████████████████████████████████████▍           | 3370/3955 [57:54<10:09,  1.04s/it]

Got Errors {'63cc4a0e84daf7410f74a48dae7a6027915e463d': 'Key 63cc4a0e84daf7410f74a48dae7a6027915e463d not found in /da5_fast/All.sha1c/commit_99.tch'}

 86%|██████████████████████████████████████████████████████████████████▋           | 3384/3955 [58:09<09:45,  1.03s/it]

Got Errors {'6772f94f806b7bfd240120a3ff7a6d53219d8fec': 'Key 6772f94f806b7bfd240120a3ff7a6d53219d8fec not found in /da5_fast/All.sha1c/commit_103.tch'}

 86%|██████████████████████████████████████████████████████████████████▊           | 3387/3955 [58:12<09:44,  1.03s/it]

Got Errors {'68878e1dd18c3bb48b10ea9d9c6e8e523d8e90cf': 'Key 68878e1dd18c3bb48b10ea9d9c6e8e523d8e90cf not found in /da5_fast/All.sha1c/commit_104.tch'}

 86%|███████████████████████████████████████████████████████████████████           | 3400/3955 [58:25<09:32,  1.03s/it]

Got Errors {'6bfacea7da8fb5bd1dbc8025b379b1f677a74d20': 'Key 6bfacea7da8fb5bd1dbc8025b379b1f677a74d20 not found in /da5_fast/All.sha1c/commit_107.tch'}

 86%|███████████████████████████████████████████████████████████████████           | 3401/3955 [58:26<09:32,  1.03s/it]

Got Errors {'6c51b83795447a1e71e9d8da72cba80b42562429': 'Key 6c51b83795447a1e71e9d8da72cba80b42562429 not found in /da5_fast/All.sha1c/commit_108.tch'}

 87%|███████████████████████████████████████████████████████████████████▊          | 3436/3955 [59:02<08:56,  1.03s/it]

Got Errors {'74c2606ba9843a75751a38f91c444bf009aee72a': 'Key 74c2606ba9843a75751a38f91c444bf009aee72a not found in /da5_fast/All.sha1c/commit_116.tch'}

 87%|███████████████████████████████████████████████████████████████████▉          | 3445/3955 [59:12<08:46,  1.03s/it]

Got Errors {'770b8e0ef278c4146b6eb055ebc0e0fb1ed4f7fa': 'Key 770b8e0ef278c4146b6eb055ebc0e0fb1ed4f7fa not found in /da5_fast/All.sha1c/commit_119.tch'}

 88%|████████████████████████████████████████████████████████████████████▎         | 3462/3955 [59:29<08:31,  1.04s/it]

Got Errors {'7bf90236fec59bb220c89e1f123ac07263f51006': 'Key 7bf90236fec59bb220c89e1f123ac07263f51006 not found in /da5_fast/All.sha1c/commit_123.tch'}

 89%|███████████████████████████████████████████████████████████████████▊        | 3530/3955 [1:00:40<07:16,  1.03s/it]

Got Errors {'8dcf58070ec47a2dc0f9e14ab8fcf4b06cda6041': 'Key 8dcf58070ec47a2dc0f9e14ab8fcf4b06cda6041 not found in /da5_fast/All.sha1c/commit_13.tch'}

 89%|███████████████████████████████████████████████████████████████████▉        | 3538/3955 [1:00:48<07:07,  1.03s/it]

Got Errors {'8feab8a3338576a4c0233022665d5b4803ee8633': 'Key 8feab8a3338576a4c0233022665d5b4803ee8633 not found in /da5_fast/All.sha1c/commit_15.tch'}

 90%|████████████████████████████████████████████████████████████████████▌       | 3567/3955 [1:01:23<06:40,  1.03s/it]

ReadTimeout:

In [6]:
len(commit_data)

35596

In [4]:
import pickle

with open("commit_data_partial.pkl", "wb") as f:
    pickle.dump(commit_data, f)

print("Saved!")

Saved!

In [7]:
# If the number of commits its not very large, you can try to get them all at the same time,
# The max batch size is 10
import time

# let us first split df['sha1'] in chunks
chunks = [df['sha1'][x:x+10] for x in range(0, len(df), 10)]

for chunk in tqdm(chunks[3567:]):  # iterate over the commits

    try:
        # commit.tch returns the same data but faster
        res, err = woc.get_values_many('commit.tch', chunk.to_list())

    except Exception as e:
        print("Skipped chunk because of error:", e)
        continue

    res = {k: v[0] for k, v in res.items()}

    # to walk around the rate limit
    time.sleep(1)

    if err:
        print('Got Errors', err)

    for commit_sha, commit in res.items():
        commit_data.append({
            'commit': commit_sha,
            'tree': commit[0],
            'parent': list(commit[1]),
            'author': commit[2][0],
            'author_time': int(commit[2][1]),
            'author_tz': commit[2][2],
            'committer': commit[3][0],
            'committer_time': int(commit[3][1]),
            'committer_tz': commit[3][2],
            'message': commit[4],
        })

df_commit_data = pd.DataFrame(commit_data)
df_commit_data = df_commit_data.merge(df, left_on='commit', right_on='sha1')
df_commit_data.to_csv('df_commit_data.csv', index=False)

df_commit_data.head(2)

 17%|█████████████▉                                                                   | 67/388 [01:18<05:29,  1.03s/it]

Got Errors {'a94a8bba742f30a364af7b3cb8120de60500fa19': 'Key a94a8bba742f30a364af7b3cb8120de60500fa19 not found in /da5_fast/All.sha1c/commit_41.tch'}

 24%|███████████████████▊                                                             | 95/388 [01:46<04:59,  1.02s/it]

Got Errors {'b186c3dcce4174bbf3f214af22bdc68442831a77': 'Key b186c3dcce4174bbf3f214af22bdc68442831a77 not found in /da5_fast/All.sha1c/commit_49.tch'}

 31%|████████████████████████▉                                                       | 121/388 [02:13<04:35,  1.03s/it]

Got Errors {'b852ba5e1dad3f61619e23929ab85f66d54e556e': 'Key b852ba5e1dad3f61619e23929ab85f66d54e556e not found in /da5_fast/All.sha1c/commit_56.tch'}

 34%|███████████████████████████                                                     | 131/388 [02:23<04:23,  1.03s/it]

Got Errors {'bb5d03f0c079f43882650e721ffe9dda87bc42d4': 'Key bb5d03f0c079f43882650e721ffe9dda87bc42d4 not found in /da5_fast/All.sha1c/commit_59.tch'}

 35%|████████████████████████████                                                    | 136/388 [02:28<04:18,  1.02s/it]

Got Errors {'bcf1b33f0ccdfb5ea1c182a1314d336dad393418': 'Key bcf1b33f0ccdfb5ea1c182a1314d336dad393418 not found in /da5_fast/All.sha1c/commit_60.tch'}

 49%|██████████████████████████████████████▉                                         | 189/388 [03:23<03:24,  1.03s/it]

Got Errors {'ca482754a9055efd97dd58135a8d85e486afc605': 'Key ca482754a9055efd97dd58135a8d85e486afc605 not found in /da5_fast/All.sha1c/commit_74.tch'}

 58%|██████████████████████████████████████████████▌                                 | 226/388 [04:01<02:46,  1.03s/it]

Got Errors {'d3b118ad7fda4b178990970bd64360485db595d9': 'Key d3b118ad7fda4b178990970bd64360485db595d9 not found in /da5_fast/All.sha1c/commit_83.tch'}

 64%|███████████████████████████████████████████████████▏                            | 248/388 [04:23<02:23,  1.03s/it]

Got Errors {'d9c1ac9d372b0efa06b756b60994e20b1cd648db': 'Key d9c1ac9d372b0efa06b756b60994e20b1cd648db not found in /da5_fast/All.sha1c/commit_89.tch'}

 67%|█████████████████████████████████████████████████████▍                          | 259/388 [04:34<02:12,  1.02s/it]

Got Errors {'dcc84f157c79ed6fe73ff04c289d1bf50f557f34': 'Key dcc84f157c79ed6fe73ff04c289d1bf50f557f34 not found in /da5_fast/All.sha1c/commit_92.tch'}

 74%|███████████████████████████████████████████████████████████▏                    | 287/388 [05:03<01:43,  1.03s/it]

Got Errors {'e4439875ac01aa30dd91cb778310645ecc753c5c': 'Key e4439875ac01aa30dd91cb778310645ecc753c5c not found in /da5_fast/All.sha1c/commit_100.tch'}

 74%|███████████████████████████████████████████████████████████▌                    | 289/388 [05:05<01:41,  1.03s/it]

Got Errors {'e5067687418e8473bf4efd013cf46b70861640e0': 'Key e5067687418e8473bf4efd013cf46b70861640e0 not found in /da5_fast/All.sha1c/commit_101.tch'}

 80%|████████████████████████████████████████████████████████████████▎               | 312/388 [05:29<01:17,  1.02s/it]

Got Errors {'eb56042650dbbe075f829eb9682ce5f6621679dc': 'Key eb56042650dbbe075f829eb9682ce5f6621679dc not found in /da5_fast/All.sha1c/commit_107.tch'}

 81%|████████████████████████████████████████████████████████████████▋               | 314/388 [05:31<01:15,  1.03s/it]

Got Errors {'ec17a7b330b7ad31a38c25212bccd44d2cc1df01': 'Key ec17a7b330b7ad31a38c25212bccd44d2cc1df01 not found in /da5_fast/All.sha1c/commit_108.tch'}

 85%|████████████████████████████████████████████████████████████████████            | 330/388 [05:47<00:59,  1.03s/it]

Got Errors {'f08a336596f79e32640ad475e2828bfb298eda9a': 'Key f08a336596f79e32640ad475e2828bfb298eda9a not found in /da5_fast/All.sha1c/commit_112.tch'}

 89%|███████████████████████████████████████████████████████████████████████▌        | 347/388 [06:05<00:41,  1.02s/it]

Got Errors {'f541c96a78e256929ef0e276c33ad3a0088ca488': 'Key f541c96a78e256929ef0e276c33ad3a0088ca488 not found in /da5_fast/All.sha1c/commit_117.tch'}

 91%|████████████████████████████████████████████████████████████████████████▊       | 353/388 [06:11<00:36,  1.04s/it]

Got Errors {'f696a1818020060a7335165844ba0e2c2e1507bf': 'Key f696a1818020060a7335165844ba0e2c2e1507bf not found in /da5_fast/All.sha1c/commit_118.tch'}

 94%|███████████████████████████████████████████████████████████████████████████     | 364/388 [06:23<00:24,  1.03s/it]

Got Errors {'f98d0619527b26b6f32c4508b45a6590d00cb320': 'Key f98d0619527b26b6f32c4508b45a6590d00cb320 not found in /da5_fast/All.sha1c/commit_121.tch'}

100%|████████████████████████████████████████████████████████████████████████████████| 388/388 [06:48<00:00,  1.05s/it]

,commit,tree,parent,author,author_time,author_tz,committer,committer_time,committer_tz,message,sha1,project
0,005873aebe765beedd8bb2cda3184f8c89279d21,530c30c4267fe94b08e339ac5f21d089d9aa5075,[f73fa70c449a304bc828303df2f81747ffea5b7e],Maria Korosteleva <mariako@kaist.ac.kr>,1617698599,+0900,Maria Korosteleva <mariako@kaist.ac.kr>,1617698599,+0900,recording stats fix\n,005873aebe765beedd8bb2cda3184f8c89279d21,maria-korosteleva_garment-pattern-estimation
1,00e5150fb1212c26300fffb603049b2d3e3c2c96,2d3bceacdf6bcfb7be781c755cec2239adc2c5a5,[e50ae07b89dc364933cc38dac534cb3cb543d47b],Maria Korosteleva <mariako@kaist.ac.kr>,1590999070,+0900,Maria Korosteleva <mariako@kaist.ac.kr>,1590999070,+0900,skirt upgrade v0.2\n,00e5150fb1212c26300fffb603049b2d3e3c2c96,maria-korosteleva_garment-pattern-estimation

In [9]:
import pickle

with open("commit_data_complete.pkl", "wb") as f:
    pickle.dump(commit_data, f)

In [10]:
project_stats = df_commit_data.groupby('project').agg(
    number_of_commits=('commit', 'nunique'),
    number_of_authors=('author', 'nunique'),
    max_time=('author_time', 'max'),
    min_time=('author_time', 'min')
)

project_stats

,number_of_commits,number_of_authors,max_time,min_time
project,,,,
baggepinnen_spectraldistances.jl,759,7,1776126985,1568771532
itowns_itowns,9190,142,1762275571,1443101686
maria-korosteleva_garment-pattern-estimation,1378,11,1736211317,1582260169
massimocimmino_pygfunction,1385,22,1771443588,1502741635
nimble-dev_nimble,9730,73,1762381653,1402585122
raysect_source,2366,33,1758534567,1376432727
serock3_master_thesis_qec_simulation,496,6,1639215098,1611075452
tf-encrypted_tf-encrypted,3165,49,1727242358,1521656591
the-virtual-brain_tvb-root,10306,136,1776180337,1401877909
xtra-computing_thundergbm,683,24,1742375195,1453180646

In [11]:
summary_df = df_commit_data[
    ['project', 'commit', 'author', 'author_time', 'message']
].copy()

summary_df.columns = [
    'project_wocid',
    'commit_sha1',
    'author',
    'time',
    'commit message'
]

summary_df.to_csv(
    'cboddick_project_summary.csv',
    sep=';',
    index=False
)

summary_df.head()

,project_wocid,commit_sha1,author,time,commit message
0,maria-korosteleva_garment-pattern-estimation,005873aebe765beedd8bb2cda3184f8c89279d21,Maria Korosteleva <mariako@kaist.ac.kr>,1617698599,recording stats fix\n
1,maria-korosteleva_garment-pattern-estimation,00e5150fb1212c26300fffb603049b2d3e3c2c96,Maria Korosteleva <mariako@kaist.ac.kr>,1590999070,skirt upgrade v0.2\n
2,maria-korosteleva_garment-pattern-estimation,013606d395963877b82b041e0b44afc36b4ec05e,mariako <mariako@kaist.ac.kr>,1621824387,transfer segmentation labels during scan imita...
3,maria-korosteleva_garment-pattern-estimation,01384216aa713d0051f13e2db0f82a1a8b23a89c,Maria Korosteleva <mariako@kaist.ac.kr>,1593576105,add feature sizes info to config\n
4,maria-korosteleva_garment-pattern-estimation,01567bf034a1e90c3525f395e6f8a9084b331035,Maria Korosteleva <mariako@kaist.ac.kr>,1606703775,"Revert ""eval stitch sides loss right away""\n\n..."